import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import InitialLoader from "./components/initialLoader";
import PageTransitionOverlay from "./components/pageTransitionOverlay";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <InitialLoader />
        <PageTransitionOverlay />
        {children}
      </body>
    </html>
  );
}
